### ISSUE TITLE
False "panic: SRC_SR_URL environment variable has not been specified" 

### ISSUE THREAD

**Issue by beckyshaw** [abraham-leal/ccloud-schema-exporter#33]
Hello,
Currently I have an issue where upon launching the docker and setting environment variables it is saying it hasn't been specified. 
The variables have been set at the start of my makefile to have three different environments use the same variable which when running a check against my credentials it runs correctly and my colleague is able to run the code, however when i run it from an M1 mac it says it hasnt been specified.

ENV ?= noenv
SRC_API_KEY ?= unknown
PWD = $(shell pwd)
REGION ?= eu-west-1
datestring = $(shell date '+%Y-%m-%d')
ifeq ($(ENV),dev)
SRC_SR_URL = REDACTED
endif

ifeq ($(ENV),nonprod)
SRC_SR_URL = REDACTED 
endif

ifeq ($(ENV),prod)
SRC_SR_URL = REDEACTED
endif

>>>
As per your documentation I ran the commands 

git clone https://github.com/abraham-leal/ccloud-schema-exporter
cd ccloud-schema-exporter
go build ./cmd/ccloud-schema-exporter/ccloud-schema-exporter.go

and

docker run \
  -e SRC_SR_URL=$SRC_SR_URL \
  -e SRC_API_KEY=$SRC_API_KEY \
  -e SRC_API_SECRET=$SRC_API_SECRET \
  -e DST_SR_URL=$DST_SR_URL \
  -e DST_API_KEY=$DST_API_KEY \
  -e DST_API_SECRET=$DST_API_SECRET \
  abrahamleal/ccloud-schema-exporter:latest

Can you please advise on where I may have missed something.

```
Status: Downloaded newer image for abrahamleal/ccloud-schema-exporter:latest
2023/06/27 14:36:44 Starting exposure of metrics on :9020/metrics
panic: SRC_SR_URL environment variable has not been specified

goroutine 1 [running]:
github.com/abraham-leal/ccloud-schema-exporter/cmd/internals.SrcGetSRUrl(0x8ea800, 0xc0001cc2a0)
        /app/cmd/internals/getInfo.go:43 +0xa5
github.com/abraham-leal/ccloud-schema-exporter/cmd/internals.NewSchemaRegistryClient(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x93ab13, 0x3, 0x8f4260)
        /app/cmd/internals/schema-registry-light-client.go:39 +0x11c
main.main()
        /app/cmd/ccloud-schema-exporter/ccloud-schema-exporter.go:108 +0xd5
```

**Comment by beckyshaw** [comment]
this is now resolved by exporting the SRC_SR_URL again.
